-- =====================================================================
-- V2 - Domain enumerations
-- Every business state machine is materialised as a PostgreSQL ENUM so
-- the database itself rejects impossible values.
-- =====================================================================

-- ---------- Security ----------
CREATE TYPE user_status          AS ENUM ('PENDING','ACTIVE','LOCKED','DISABLED','ARCHIVED');

-- ---------- School / academic ----------
CREATE TYPE school_status        AS ENUM ('ACTIVE','INACTIVE','ARCHIVED');
CREATE TYPE academic_year_status AS ENUM ('DRAFT','OPEN','ACTIVE','CLOSING','CLOSED','ARCHIVED');
CREATE TYPE term_type            AS ENUM ('TERM','SEMESTER','TRIMESTER','CUSTOM');
CREATE TYPE term_status          AS ENUM ('PLANNED','OPEN','GRADE_ENTRY','VALIDATION','CLOSED');
CREATE TYPE classroom_status     AS ENUM ('DRAFT','ACTIVE','CLOSED','ARCHIVED');
CREATE TYPE capacity_status      AS ENUM ('AVAILABLE','WARNING','FULL','OVER_CAPACITY');
CREATE TYPE subject_category     AS ENUM ('SCIENCE','LITERATURE','LANGUAGE','ARTS','SPORT','TECHNICAL','RELIGION','CIVICS','OTHER');
CREATE TYPE common_status        AS ENUM ('ACTIVE','INACTIVE','ARCHIVED');

-- ---------- People ----------
CREATE TYPE gender               AS ENUM ('MALE','FEMALE','OTHER');
CREATE TYPE student_status       AS ENUM ('APPLICANT','ADMITTED','ACTIVE','SUSPENDED','WITHDRAWN','GRADUATED','TRANSFERRED','ARCHIVED');
CREATE TYPE guardian_relationship AS ENUM ('FATHER','MOTHER','TUTOR','LEGAL_REPRESENTATIVE','GRANDPARENT','SIBLING','OTHER_AUTHORIZED');
CREATE TYPE teacher_status       AS ENUM ('ACTIVE','ON_LEAVE','SUSPENDED','RESIGNED','RETIRED','ARCHIVED');
CREATE TYPE staff_status         AS ENUM ('ACTIVE','ON_LEAVE','SUSPENDED','RESIGNED','ARCHIVED');
CREATE TYPE contract_type        AS ENUM ('PERMANENT','FIXED_TERM','HOURLY','INTERN','VOLUNTEER','OTHER');

-- ---------- Admission / enrollment ----------
CREATE TYPE admission_status     AS ENUM ('DRAFT','SUBMITTED','UNDER_REVIEW','TESTED','ACCEPTED','WAITLISTED','REJECTED','WITHDRAWN','CONVERTED');
CREATE TYPE enrollment_status    AS ENUM ('DRAFT','PENDING','VALIDATED','ACTIVE','SUSPENDED','CANCELLED','COMPLETED','TRANSFERRED');
CREATE TYPE enrollment_kind      AS ENUM ('NEW','RE_ENROLLMENT','TRANSFER_IN');

-- ---------- Timetable / attendance ----------
CREATE TYPE assignment_status    AS ENUM ('DRAFT','ACTIVE','SUSPENDED','ENDED');
CREATE TYPE timetable_status     AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
CREATE TYPE course_session_status AS ENUM ('PLANNED','IN_PROGRESS','DONE','CANCELLED','POSTPONED');
CREATE TYPE attendance_session_status AS ENUM ('OPEN','SUBMITTED','VALIDATED','LOCKED');
CREATE TYPE attendance_status    AS ENUM ('PRESENT','ABSENT','LATE','EXCUSED_ABSENCE','EXCUSED_LATE','LEFT_EARLY');

-- ---------- Assessment / grades ----------
CREATE TYPE assessment_type      AS ENUM ('HOMEWORK','QUIZ','TEST','EXAM','ORAL','PRACTICAL','PROJECT','CONTINUOUS_ASSESSMENT','OTHER');
CREATE TYPE assessment_status    AS ENUM ('DRAFT','PLANNED','OPEN','GRADING','SUBMITTED','VALIDATED','PUBLISHED','CANCELLED');
CREATE TYPE grade_status         AS ENUM ('DRAFT','SUBMITTED','VALIDATED','PUBLISHED');
CREATE TYPE report_card_status   AS ENUM ('DRAFT','GENERATED','VALIDATED','PUBLISHED','ARCHIVED');
CREATE TYPE council_status       AS ENUM ('PLANNED','IN_PROGRESS','CLOSED','ARCHIVED');
CREATE TYPE promotion_decision_type AS ENUM ('PASS','REPEAT','PROMOTED','GRADUATED','TRANSFER_RECOMMENDED','ORIENTATION_REQUIRED','PENDING_DECISION');

-- ---------- Discipline ----------
CREATE TYPE incident_type        AS ENUM ('BEHAVIOR','VIOLENCE','CHEATING','ABSENTEEISM','LATENESS','PROPERTY_DAMAGE','OTHER');
CREATE TYPE incident_severity    AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE incident_status      AS ENUM ('REPORTED','UNDER_REVIEW','ACTION_TAKEN','CLOSED','CANCELLED');
CREATE TYPE disciplinary_action_type AS ENUM ('WARNING','DETENTION','PARENT_MEETING','SUSPENSION','EXPULSION','OTHER');

-- ---------- Finance ----------
CREATE TYPE fee_category         AS ENUM ('REGISTRATION','TUITION','EXAM','ACTIVITY','UNIFORM','TRANSPORT','CANTEEN','OTHER');
CREATE TYPE fee_recurrence       AS ENUM ('ONE_TIME','ANNUAL','TERM','MONTHLY');
CREATE TYPE student_fee_status   AS ENUM ('PAID','PARTIALLY_PAID','DUE','OVERDUE','WAIVED','CANCELLED');
CREATE TYPE invoice_status       AS ENUM ('DRAFT','ISSUED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED');
CREATE TYPE payment_method       AS ENUM ('CASH','BANK_TRANSFER','CARD','MOBILE_MONEY','CHEQUE','OTHER');
CREATE TYPE payment_status       AS ENUM ('PENDING','VALIDATED','CANCELLED','REVERSED','FAILED');
CREATE TYPE discount_type        AS ENUM ('PERCENTAGE','FIXED_AMOUNT');
CREATE TYPE scholarship_status   AS ENUM ('REQUESTED','GRANTED','SUSPENDED','REVOKED','EXPIRED');
CREATE TYPE cash_session_status  AS ENUM ('OPEN','CLOSED','RECONCILED');

-- ---------- Cross-cutting ----------
CREATE TYPE notification_channel AS ENUM ('IN_APP','EMAIL','SMS','PUSH');
CREATE TYPE notification_status  AS ENUM ('PENDING','SENT','DELIVERED','READ','FAILED','CANCELLED');
CREATE TYPE alert_type           AS ENUM ('CLASS_CAPACITY_WARNING','CLASS_FULL','HIGH_ABSENTEEISM','STUDENT_REPEATED_ABSENCE','GRADE_ENTRY_DELAY','REPORT_CARD_PENDING','PAYMENT_DUE','PAYMENT_OVERDUE','TIMETABLE_CONFLICT','DISCIPLINE_INCIDENT');
CREATE TYPE alert_severity       AS ENUM ('INFO','WARNING','CRITICAL');
CREATE TYPE alert_status         AS ENUM ('OPEN','ACKNOWLEDGED','RESOLVED','DISMISSED');
CREATE TYPE document_type        AS ENUM ('STUDENT_FILE','SCHOOL_CERTIFICATE','ENROLLMENT_ATTESTATION','REPORT_CARD','TRANSCRIPT','RECEIPT','INVOICE','FINANCIAL_STATEMENT','SUMMONS','STUDENT_CARD','OTHER');
CREATE TYPE document_status      AS ENUM ('DRAFT','GENERATED','ISSUED','REVOKED');
CREATE TYPE audit_action         AS ENUM ('CREATE','UPDATE','DELETE','READ_SENSITIVE','VALIDATE','PUBLISH','CANCEL','LOGIN','LOGIN_FAILED','LOGOUT','PERMISSION_CHANGE','EXPORT','IMPORT');
CREATE TYPE outbox_status        AS ENUM ('PENDING','PROCESSING','PROCESSED','FAILED');
CREATE TYPE day_of_week          AS ENUM ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY');
