package ci.company.eduops.finance.domain;

import ci.company.eduops.academicyear.domain.AcademicYear;
import ci.company.eduops.common.entity.BaseEntity;
import ci.company.eduops.common.util.MoneyUtils;
import ci.company.eduops.enrollment.domain.Enrollment;
import ci.company.eduops.student.domain.Student;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

/**
 * What a specific pupil owes for one instalment.
 *
 * <p>Rule 8: {@code amountRemaining} is a generated column derived from
 * {@code amountDue - amountPaid}; no code path can desynchronise it.</p>
 */
@Entity
@Table(name = "student_fee")
@Getter
@Setter
public class StudentFee extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "enrollment_id", nullable = false)
    private Enrollment enrollment;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "academic_year_id", nullable = false)
    private AcademicYear academicYear;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "fee_type_id", nullable = false)
    private FeeType feeType;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fee_schedule_id")
    private FeeSchedule feeSchedule;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "instalment_id")
    private FeeScheduleInstalment instalment;

    @Column(name = "discount_id")
    private UUID discountId;

    @Column(name = "scholarship_id")
    private UUID scholarshipId;

    @Column(name = "label", nullable = false, length = 150)
    private String label;

    @Column(name = "sequence", nullable = false)
    private int sequence = 1;

    @Column(name = "gross_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal grossAmount = MoneyUtils.ZERO;

    @Column(name = "discount_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal discountAmount = MoneyUtils.ZERO;

    @Column(name = "amount_due", nullable = false, precision = 15, scale = 2)
    private BigDecimal amountDue = MoneyUtils.ZERO;

    @Column(name = "amount_paid", nullable = false, precision = 15, scale = 2)
    private BigDecimal amountPaid = MoneyUtils.ZERO;

    /** Generated by PostgreSQL: amountDue - amountPaid. Never written by Java. */
    @Column(name = "amount_remaining", insertable = false, updatable = false,
            precision = 15, scale = 2)
    private BigDecimal amountRemaining;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency = "XOF";

    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", nullable = false, columnDefinition = "student_fee_status")
    private StudentFeeStatus status = StudentFeeStatus.DUE;

    @Column(name = "waived_reason")
    private String waivedReason;

    @Column(name = "waived_by")
    private UUID waivedBy;

    /** Outstanding balance of this line, computed and never stored by Java. */
    public BigDecimal outstanding() {
        return MoneyUtils.subtract(amountDue, amountPaid);
    }

    /** Applies part of a payment and recomputes the resulting status. */
    public void allocate(BigDecimal amount) {
        this.amountPaid = MoneyUtils.add(this.amountPaid, amount);
        refreshStatus();
    }

    public void deallocate(BigDecimal amount) {
        this.amountPaid = MoneyUtils.max(MoneyUtils.subtract(this.amountPaid, amount),
                MoneyUtils.ZERO);
        refreshStatus();
    }

    public void refreshStatus() {
        if (status == StudentFeeStatus.WAIVED || status == StudentFeeStatus.CANCELLED) {
            return;
        }
        BigDecimal remaining = outstanding();
        if (MoneyUtils.isZeroOrLess(remaining)) {
            this.status = StudentFeeStatus.PAID;
        } else if (MoneyUtils.isPositive(amountPaid)) {
            this.status = isPastDue() ? StudentFeeStatus.OVERDUE : StudentFeeStatus.PARTIALLY_PAID;
        } else {
            this.status = isPastDue() ? StudentFeeStatus.OVERDUE : StudentFeeStatus.DUE;
        }
    }

    public boolean isPastDue() {
        return dueDate != null && dueDate.isBefore(LocalDate.now());
    }

    public void recomputeAmountDue() {
        this.amountDue = MoneyUtils.subtract(grossAmount, discountAmount);
    }
}
